server:
  port: 18080
logging:
#  pattern:
#    console: %d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} -%kvp- %msg%n
  level:
    root: warn
    org.springframework: error
    com.github.sivaone.springwsclient: trace
app:
  soap-url: "http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso"